{{- range $issuer := .Values.issuers }}
{{ $_ := set $issuer "namespace" ($issuer.namespace | default $.Release.Namespace) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $issuer.spec | keys | first }}-{{ $issuer.name }}
  namespace: {{ $issuer.namespace }}
  {{- if $issuer.metadata }}{{- with $issuer.metadata.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}{{- end }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    {{- if $issuer.metadata }}{{- with $issuer.metadata.labels }}{{ toYaml . | nindent 4 }}{{ end }}{{ end }}
spec: {{ include "issuer.spec.render" (dict "root" $ "issuer" $issuer) | nindent 2 }}
{{- end }}
{{- range $issuer := .Values.clusterIssuers }}
{{ $_ := unset $issuer "namespace" }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $issuer.spec | keys | first }}-{{ $issuer.name }}
  {{- if $issuer.metadata }}{{- with $issuer.metadata.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}{{- end }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
    {{- with $.Values.global.commonLabels }}{{ toYaml . | nindent 4 }}{{ end }}
    {{- if $issuer.metadata }}{{- with $issuer.metadata.labels }}{{ toYaml . | nindent 4 }}{{ end }}{{ end }}
spec: {{ include "issuer.spec.render" (dict "root" $ "issuer" $issuer) | nindent 2 }}
{{- end }}
