{{- range $name, $issuer := .Values.issuers.acme }}
{{- if $issuer }}
{{ $_ := set $issuer "type" "acme" }}
{{ $_ = set $issuer "name" $name }}
---
apiVersion: cert-manager.io/v1
{{- if $issuer.clusterIssuer }}
kind: ClusterIssuer
{{- else }}
kind: Issuer
{{- end }}
metadata:
  name: {{ $issuer.name }}
  {{- if not $issuer.clusterIssuer }}
  namespace: {{ $issuer.namespace | default $.Release.Namespace }}
  {{- end }}
  {{- if $issuer.annotations }}
  annotations:
    {{- with $issuer.annotations }}
    {{- toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
  labels: {{ include "issuer.labels" $ | nindent 4 }}
    {{- with $issuer.labels }}
    {{- toYaml . | indent 4 }}
    {{- end }}
spec:
  acme: {{ if $issuer.spec }}{{ include "issuer.spec.render" (merge dict $ $issuer) | nindent 4 }}{{ else }}{}{{ end }}
{{- if .credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "issuer.crendentials.name" $issuer }}
  namespace: {{ include "issuer.crendentials.namespace" (merge dict $ $issuer) }}
  labels: {{ include "issuer.labels" $ | nindent 4 }}
    issuer.cert-manager.io/name: {{ $issuer.name }}
type: Opaque
stringData: {{ $issuer.credentials | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
