{{- range $name, $issuer := .Values.issuers.selfsigned }}
{{- if $issuer }}
{{ $_ := set $issuer "type" "selfsigned" }}
{{ $_ = set $issuer "name" $name }}
---
apiVersion: cert-manager.io/v1
{{- if $issuer.clusterIssuer }}
kind: ClusterIssuer
{{- else }}
kind: Issuer
{{- end }}
metadata:
  name: {{ $issuer.name }}
  {{- if not $issuer.clusterIssuer }}
  namespace: {{ $issuer.namespace | default $.Release.Namespace }}
  {{- end }}
  {{- if $issuer.annotations }}
  annotations:
    {{- with $issuer.annotations }}
    {{- toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
  labels: {{ include "issuer.labels" $ | nindent 4 }}
    {{- with $issuer.labels }}
    {{- toYaml . | indent 4 }}
    {{- end }}
spec:
  selfSigned: {{ if $issuer.spec }}{{ include "issuer.spec.render" (merge dict $ $issuer) | nindent 4 }}{{ else }}{}{{ end }}
{{- end }}
{{- end }}
