---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/security.container.yml
      - images/**/Dockerfile
  push:
    branches: [main]
    paths:
      - images/**/Dockerfile

jobs:
  updated_container:
    name: List updated containers
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 3
      - uses: tj-actions/changed-files@7f2aa19bdcf4a00195671e368091a1e32a694ac5 # v35.5.2
        id: changed-files
        with:
          files: |
            **/Dockerfile
          json: true
      - id: set-matrix
        run: echo "matrix={\"dockerfile\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  trivy:
    name: Trivy scan (${{ matrix.dockerfile }})
    needs: [updated_container]
    runs-on: ubuntu-latest
    if: needs.updated_container.outputs.matrix != '{"dockerfile":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.updated_container.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2.1.0
      - uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2.4.1
        with:
          version: latest

      - uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # 0.9.1
        with:
          hide-progress: false
          scan-ref: ${{ matrix.dockerfile }}
          scan-type: config

      - uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # 0.9.1
        with:
          exit-code: '1'
          format: sarif
          hide-progress: false
          output: trivy-results.sarif
          scan-ref: ${{ matrix.dockerfile }}
          scan-type: config
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL # NOTE: avoid reporting LOW issues
      - uses: github/codeql-action/upload-sarif@5794d966f2616fdb53b22968a7546fc36d343ec3 # tag=codeql-bundle-20221211
        if: always()
        with:
          category: trivy-container-syntax
          sarif_file: trivy-results.sarif

      - name: Get Dockerfile directory
        id: dockerfile
        run: |
          export CONTEXT=${DOCKERFILE%/*}
          export IMAGE=${CONTEXT#*/}
          echo "context=${CONTEXT}" | tee --append "${GITHUB_OUTPUT}"
          echo "image=${IMAGE}" | tee --append "${GITHUB_OUTPUT}"
        env:
          DOCKERFILE: ${{ matrix.dockerfile }}
      - uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: ${{ steps.dockerfile.outputs.context }}
          platforms: linux/amd64
          load: true
          tags: ${{ steps.dockerfile.outputs.image }}:${{ github.sha }}-trivy

      - uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # 0.9.1
        with:
          hide-progress: false
          image-ref: ${{ steps.dockerfile.outputs.image }}:${{ github.sha }}-trivy
          scan-type: image

      - uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 # 0.9.1
        with:
          format: sarif
          hide-progress: false
          image-ref: ${{ steps.dockerfile.outputs.image }}:${{ github.sha }}-trivy
          output: trivy-results.sarif
          scan-type: image
          severity: UNKNOWN,MEDIUM,HIGH,CRITICAL # NOTE: avoid reporting LOW issues
      - uses: github/codeql-action/upload-sarif@5794d966f2616fdb53b22968a7546fc36d343ec3 # tag=codeql-bundle-20221211
        if: always()
        with:
          category: trivy-container
          sarif_file: trivy-results.sarif
