---
name: Test (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/test.helm.yml
      - charts/**
  schedule:
    - cron: 0 2 * * 1,3

jobs:
  updated_charts:
    name: List updated charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 3
      - uses: tj-actions/changed-files@7f2aa19bdcf4a00195671e368091a1e32a694ac5 # v35.5.2
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/**
          json: true
      - id: set-matrix
        run: echo "matrix={\"chart\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  # Test all charts using the official chart-testing CLI.
  chart_testing:
    name: Chart testing
    needs: [updated_charts]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && needs.updated_charts.outputs.matrix != '{"chart":[]}'
    strategy:
      matrix: ${{ fromJSON(needs.updated_charts.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v3.3.0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # tag=v2.3.1
      - uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # tag=v1.5.0

      - name: Install pre-required resources
        run: just ct_pre_install
        working-directory: ${{ matrix.chart }}
      - name: Run chart-testing (install)
        run: ct install --charts ${{ matrix.chart }}
        env:
          HELM_CONFIG_HOME: ${{ github.workspace }}/.ct


  # Test all charts using the official chart-testing CLI.
  chart_testing_all:
    name: Chart testing
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v3.3.0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # tag=v2.3.1
      - uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # tag=v1.5.0

      - name: Install pre-required resources
        run: just ct_pre_install
      - name: Run chart-testing (install)
        if: github.event_name == 'push'
        run: ct install --all
        env:
          HELM_CONFIG_HOME: ${{ github.workspace }}/.ct
